# Generated by Django 3.2 on 2021-05-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id_producer', models.AutoField(primary_key=True, serialize=False)),
                ('registro_animal', models.CharField(max_length=5)),
                ('volume', models.FloatField()),
                ('dia_horario', models.DateTimeField()),
                ('tempo_armazenamento', models.FloatField()),
                ('temperatura_armazenamento', models.FloatField()),
                ('ph', models.FloatField()),
            ],
        ),
    ]
