# Generated by Django 3.1.7 on 2021-04-17 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('index', models.IntegerField()),
                ('current_transactions', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nonce', models.IntegerField()),
                ('hash', models.TextField(primary_key=True, serialize=False, verbose_name='b642aaecf583ab65d2f4edc70e1ce607b97990c938c990291ae9ec9db04c610f')),
                ('previous_hash', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blockchain.block')),
            ],
        ),
    ]
