# Generated by Django 3.2 on 2021-04-17 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_rename_block_blockchain'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blockchain',
            new_name='Block',
        ),
    ]
