# Generated by Django 3.2 on 2021-04-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_rename_blockchain_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='hash',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
