# Generated by Django 3.2 on 2021-04-19 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_alter_block_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='previous_hash',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='blockchain.block'),
        ),
    ]
