# Generated by Django 3.2 on 2021-04-19 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0006_alter_block_previous_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='previous_hash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='blockchain.block'),
        ),
    ]
